export default [
    {
        id: 1,
        name: 'Soorya',
        age: 20,
        city: 'durgapur',
        attr1: 'val1',
        attr2: 'val2',
        attr3: 'val3',
    },
    {
        id: 2,
        name: 'Lokesh',
        age: 20,
        city: 'chennai',
        attr1: 'val1',
        attr2: 'val2',
        attr3: 'val3',
    },
    {
        id: 3,
        name: 'Adithya',
        age: 20,
        city: 'chennai',
        attr1: 'val1',
        attr2: 'val2',
        attr3: 'val3',
    },
    {
        id: 4,
        name: 'Soorya',
        age: 20,
        city: 'durgapur',
        attr1: 'val1',
        attr2: 'val2',
        attr3: 'val3',
    },
    {
        id: 5,
        name: 'Lokesh',
        age: 20,
        city: 'chennai',
        attr1: 'val1',
        attr2: 'val2',
        attr3: 'val3',
    },
    {
        id: 6,
        name: 'Adithya',
        age: 20,
        city: 'chennai',
        attr1: 'val1',
        attr2: 'val2',
        attr3: 'val3',
    }
]