
DROP TABLE CANDIDATE;
DROP TABLE VOTER;
DROP TABLE BOOTH;
DROP TABLE CONSTITUENCY;
DROP TABLE PARTY;
DROP TABLE DISTRICT;


CREATE TABLE DISTRICT (
    ID NUMBER(3) CONSTRAINT DISTRICTS_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    NO_OF_CONSTITUENCIES NUMBER(4),
    POPULATION NUMBER(20)
);

INSERT INTO DISTRICT VALUES(1,'CHENNAI', 20, 300000);
INSERT INTO DISTRICT VALUES(2,'MUMBAI', 30, 400000);
INSERT INTO DISTRICT VALUES(3,'DELHI', 40, 500000);
INSERT INTO DISTRICT VALUES(4,'KOLKATA', 50, 600000);

CREATE TABLE PARTY(
    ID NUMBER(3) CONSTRAINT PARTY_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    DO_ESTAB DATE,
    LEADER VARCHAR2(20),
    NO_OF_CANDIDATES NUMBER(4)
);

CREATE TABLE CONSTITUENCY(
    ID NUMBER(5) CONSTRAINT CONSTITUENCIES_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    DISTRICT NUMBER(3) CONSTRAINT CONS_DIST_FK REFERENCES DISTRICT(ID),
    RESERVATION VARCHAR2(10), -- NOT SURE ABOUT THE DATA TYPE
    CURR_RULING NUMBER(3) CONSTRAINT CONST_PARTY_FK REFERENCES PARTY(ID),
    NO_OF_CONTESTANTS NUMBER(3),
    POPULATION NUMBER(20)
);

CREATE TABLE BOOTH(
    ID NUMBER(10) CONSTRAINT BOOTH_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    CONSTITUENCY NUMBER(5) CONSTRAINT BOOTH_CONST_FK REFERENCES CONSTITUENCY(ID),
    POPULATION NUMBER(20)
);

CREATE TABLE VOTER(
    ID NUMBER(10) CONSTRAINT VOTER_PK PRIMARY KEY,
    NAME VARCHAR2(20),
    FATHERS_NAME VARCHAR2(20),
    DOB DATE,
    GENDER VARCHAR2(1),
    CATEGORY VARCHAR2(5),
    BOOTH NUMBER(10) CONSTRAINT VOTER_BOOTH_FK REFERENCES BOOTH(ID)
);

CREATE TABLE CANDIDATE(
    ID NUMBER(10) CONSTRAINT CAND_PK PRIMARY KEY,
    NAME VARCHAR2(20),
    PARTY NUMBER(3) CONSTRAINT CAND_PARTY_FK REFERENCES PARTY(ID),
    AGE NUMBER(3),
    CONSTITUENCY NUMBER(5) CONSTRAINT CAND_CONS_FK REFERENCES CONSTITUENCY(ID),
    QOUTA VARCHAR2(5)
);