DROP TABLE CANDIDATE;
DROP TABLE VOTER;
DROP TABLE BOOTH;
DROP TABLE CONSTITUENCY;
DROP TABLE PARTY;
DROP TABLE DISTRICT;


CREATE TABLE DISTRICT (
    ID NUMBER(3) CONSTRAINT DISTRICTS_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    NO_OF_CONSTITUENCIES NUMBER(4),
    POPULATION NUMBER(20)
);


CREATE TABLE PARTY(
    ID NUMBER(3) CONSTRAINT PARTY_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    DO_ESTAB VARCHAR(20),
    LEADER VARCHAR2(20),
    NO_OF_CANDIDATES NUMBER(4)
);

CREATE TABLE CONSTITUENCY(
    ID NUMBER(5) CONSTRAINT CONSTITUENCIES_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    DISTRICT NUMBER(3) CONSTRAINT CONS_DIST_FK REFERENCES DISTRICT(ID) ON DELETE CASCADE,
    RESERVATION VARCHAR2(10), -- NOT SURE ABOUT THE DATA TYPE
    CURR_RULING NUMBER(3) CONSTRAINT CONST_PARTY_FK REFERENCES PARTY(ID) ON DELETE CASCADE,
    NO_OF_CONTESTANTS NUMBER(3),
    POPULATION NUMBER(20)
);

CREATE TABLE BOOTH(
    ID NUMBER(10) CONSTRAINT BOOTH_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    CONSTITUENCY NUMBER(5) CONSTRAINT BOOTH_CONST_FK REFERENCES CONSTITUENCY(ID) ON DELETE CASCADE,
    POPULATION NUMBER(20)
);

CREATE TABLE VOTER(
    ID NUMBER(10) CONSTRAINT VOTER_PK PRIMARY KEY,
    NAME VARCHAR2(20),
    FATHERS_NAME VARCHAR2(20),
    DOB VARCHAR(20),
    GENDER VARCHAR2(1),
    CATEGORY VARCHAR2(5),
    BOOTH NUMBER(10) CONSTRAINT VOTER_BOOTH_FK REFERENCES BOOTH(ID) ON DELETE CASCADE
);

CREATE TABLE CANDIDATE(
    ID NUMBER(10) CONSTRAINT CAND_PK PRIMARY KEY,
    NAME VARCHAR2(20),
    PARTY NUMBER(3) CONSTRAINT CAND_PARTY_FK REFERENCES PARTY(ID) ON DELETE CASCADE,
    AGE NUMBER(3),
    CONSTITUENCY NUMBER(5) CONSTRAINT CAND_CONS_FK REFERENCES CONSTITUENCY(ID) ON DELETE CASCADE,
    QOUTA VARCHAR2(5)
);
