INSERT INTO DISTRICT VALUES (1, 'Chennai', 	3, 40);
INSERT INTO DISTRICT VALUES (2, 'Coimbatore', 	2, 23);
INSERT INTO DISTRICT VALUES (3, 'Kancheepuram', 	1, 6);
INSERT INTO DISTRICT VALUES (4, 'Madurai', 	2, 11);
INSERT INTO DISTRICT VALUES (5, 'Tiruchirapalli', 1, 12);


INSERT INTO PARTY VALUES (1,	'AIADMK',	'17-OCT-1972',	'E Palaniswami',	8);
INSERT INTO PARTY VALUES (2,	'DMK',		'17-SEP-1949',	'MK Stalin',		5);
INSERT INTO PARTY VALUES (3,	'BJP',		'06-APR-1980',	'Tamilisai S.',		1);
INSERT INTO PARTY VALUES (4,	'INC',		'12-NOV-1969',	'KS Alagiri',		2);
INSERT INTO PARTY VALUES (5,	'BSP',		'14-APR-1984',	'Armstrong K.',		2);
INSERT INTO PARTY VALUES (6,	'MNM',		'21-FEB-2018',	'Kamal Haasan',		3);
INSERT INTO PARTY VALUES (999,	'Independent',		NULL,	'N/A',			NULL);				


INSERT INTO CONSTITUENCY VALUES (1, 'Egmore', 		1, 'SC', 2, 2, 11);
INSERT INTO CONSTITUENCY VALUES (2, 'Anna Nagar', 	1, NULL, 2, 2, 12);
INSERT INTO CONSTITUENCY VALUES (3, 'Velachery', 		1, NULL, 2, 3, 17);
INSERT INTO CONSTITUENCY VALUES (4, 'Mettupalayam', 	2, NULL, 1, 2, 11);
INSERT INTO CONSTITUENCY VALUES (5, 'Pollachi', 		2, NULL, 1, 2, 12);
INSERT INTO CONSTITUENCY VALUES (6, 'Sriperumbudur', 	3, NULL, 1, 1, 6);
INSERT INTO CONSTITUENCY VALUES (7, 'Sholavandan',	4, 'SC', 1, 1, 6);
INSERT INTO CONSTITUENCY VALUES (8, 'Usilampatti', 	4, NULL, 1, 1, 5);
INSERT INTO CONSTITUENCY VALUES (9, 'Srirangam', 		5, NULL, 1, 2, 12);


INSERT INTO BOOTH VALUES (1, 	'Museum Theatre', 		1, 5);
INSERT INTO BOOTH VALUES (2, 	'Chennai Middle School', 	1, 6);
INSERT INTO BOOTH VALUES (3, 	'Krishnasamy School', 		2, 6);
INSERT INTO BOOTH VALUES (4, 	'DG Vaishnav College', 		2, 6);
INSERT INTO BOOTH VALUES (5, 	'Besant School', 		3, 6);
INSERT INTO BOOTH VALUES (6, 	'St. Brittos Academy',		3, 5);
INSERT INTO BOOTH VALUES (7, 	'Chitkala School', 		3, 6);
INSERT INTO BOOTH VALUES (8, 	'Panchayat Union School',	4, 6);
INSERT INTO BOOTH VALUES (9, 	'Sarguru Adivasi School', 	4, 5);
INSERT INTO BOOTH VALUES (10, 	'Govt. High School', 		5, 6);
INSERT INTO BOOTH VALUES (11, 	'VSRA Municipal High School',	5, 6);
INSERT INTO BOOTH VALUES (12, 	'Govt. Adi Dravidar Welfare',	6, 6);
INSERT INTO BOOTH VALUES (13, 	'Pt. Union Elementary School',	7, 6);
INSERT INTO BOOTH VALUES (14, 	'Govt. Kallar High School', 	8, 5);
INSERT INTO BOOTH VALUES (15, 	'The High School',		9, 6);
INSERT INTO BOOTH VALUES (16, 	'Community Hall', 		9, 6);


INSERT INTO VOTER VALUES (1,	'Shanmugam R.',		'Ravindran C.',		'12-DEC-1963', 'M', NULL, 1);
INSERT INTO VOTER VALUES (2,	'Ravindran C.',		'Chandran C.',		'10-OCT-1938', 'M', NULL, 1);
INSERT INTO VOTER VALUES (3,	'Raveena S.',		'Sivakumar H.',		'12-JAN-1995', 'F', NULL, 1);
INSERT INTO VOTER VALUES (4,	'Anirudh R.',		'Ramanathan A.',	'02-JUN-1984', 'M', NULL, 1);
INSERT INTO VOTER VALUES (5,	'Arivazhagan K.',	'Kripakaran M.',	'13-MAY-1960', 'M', NULL, 1);
INSERT INTO VOTER VALUES (6,	'Shanthi S.',		'Sukumar U.',		'30-MAR-1957', 'F', 'SC', 2);
INSERT INTO VOTER VALUES (7,	'Elango R.',		'Ravi Kumar C.',	'12-DEC-1976', 'M', NULL, 2);
INSERT INTO VOTER VALUES (8,	'Abdul Kadir',		'Abbas Amir',		'12-JUL-1990', 'M', NULL, 2);
INSERT INTO VOTER VALUES (9,	'Rahul Jain',		'Prakash Jain',		'15-APR-1997', 'M', NULL, 2);
INSERT INTO VOTER VALUES (10,	'Rohan Jain',		'Prakash Jain',		'15-APR-1934', 'M', NULL, 2);
INSERT INTO VOTER VALUES (11,	'Aarthi S.',		'Suresh V.',		'22-SEP-1962', 'F', NULL, 2);
INSERT INTO VOTER VALUES (12,	'Umesh M.',		'Mohan Balaji',		'02-DEC-1943', 'M', NULL, 3);
INSERT INTO VOTER VALUES (13,	'Srivatsan R.',		'Ramanan S.',		'31-MAY-1999', 'M', NULL, 3);
INSERT INTO VOTER VALUES (14,	'Janardhan C.',		'Chandrasekhar P.',	'01-AUG-2000', 'M', NULL, 3);
INSERT INTO VOTER VALUES (15,	'Shruti Jeyaram',	'Jeyaram Balakrishnan',	'04-JAN-1988', 'F', NULL, 3);
INSERT INTO VOTER VALUES (16,	'Balachander G.',	'Gopalarathnam D.',	'30-MAR-1969', 'M', NULL, 3);
INSERT INTO VOTER VALUES (17,	'Dhanasekaran S.',	'Sriraman B.',		'28-FEB-1973', 'M', NULL, 3);
INSERT INTO VOTER VALUES (18,	'R. R. Tamizhan',	'Ravi Raman S.',	'26-APR-1982', 'M', NULL, 4);
INSERT INTO VOTER VALUES (19,	'Selvi',		'Gopalswamy',		'17-MAY-1971', 'F', 'SC', 4);
INSERT INTO VOTER VALUES (20,	'Ambika D.',		'Dhanush M.',		'19-JUN-1999', 'F', NULL, 4);
INSERT INTO VOTER VALUES (21,	'Joseph Karunakar',	'Stephen Ramesh',	'12-SEP-1971', 'M', NULL, 4);
INSERT INTO VOTER VALUES (22,	'Maari V.',		'Vijay C.',		'11-OCT-1970', 'M', NULL, 4);
INSERT INTO VOTER VALUES (23,	'Ajith Kumar',		'Aravindan T. S.',	'10-AUG-1950', 'M', NULL, 4);
INSERT INTO VOTER VALUES (24,	'Supraja Sridhar',	'Sridhar Venkat',	'24-NOV-1965', 'F', NULL, 5);
INSERT INTO VOTER VALUES (25,	'Ilamparithi D.',	'Dhanapandi J.',	'23-JAN-1964', 'M', NULL, 5);
INSERT INTO VOTER VALUES (26,	'Md. Ahmed',		'Md. Baasha',		'11-DEC-1933', 'M', 'SC', 5);
INSERT INTO VOTER VALUES (27,	'Shadab Khan',		'Ameer Khan',		'21-JUL-1961', 'M', NULL, 5);
INSERT INTO VOTER VALUES (28,	'Jacob Johnson',	'Arnold Johnson',	'10-JUN-1961', 'M', NULL, 5);
INSERT INTO VOTER VALUES (29,	'Josephine Varsha',	'Arnold Johnson',	'01-AUG-1965', 'F', NULL, 5);
INSERT INTO VOTER VALUES (30,	'Mandeep Singh',	'Navjot Singh',		'02-MAR-1960', 'M', NULL, 6);
INSERT INTO VOTER VALUES (31,	'Pooja Kaur',		'Mandeep Singh',	'03-APR-1975', 'F', NULL, 6);
INSERT INTO VOTER VALUES (32,	'Anbalagan K.',		'Kuppusamy C.',		'04-JAN-1957', 'M', NULL, 6);
INSERT INTO VOTER VALUES (33,	'Savitha Nair',		'Kumar Vishwas',	'11-FEB-1965', 'F', NULL, 6);
INSERT INTO VOTER VALUES (34,	'Srilatha V.',		'Vikas Krishnan',	'10-MAY-1981', 'F', NULL, 6);
INSERT INTO VOTER VALUES (35,	'Avik Sriram',		'Sriram Kannan',	'29-JUL-1987', 'M', NULL, 7);
INSERT INTO VOTER VALUES (36,	'Surya M. K.',		'Mohan Kumaran P. R.',	'31-MAR-2002', 'M', NULL, 7);
INSERT INTO VOTER VALUES (37,	'P. S. Ravindran',	'Pennathur Subramani',	'11-SEP-1990', 'M', NULL, 7);
INSERT INTO VOTER VALUES (38,	'Vaageesa Datta',	'Srikumar S.',		'15-NOV-1961', 'M', 'SC', 7);
INSERT INTO VOTER VALUES (39,	'Chandramouleeshwaran',	'Raghuraman',		'18-NOV-1950', 'M', NULL, 7);
INSERT INTO VOTER VALUES (40,	'Aasif Javed',		'Babar Javed',		'15-AUG-1947', 'M', NULL, 7);
INSERT INTO VOTER VALUES (41,	'Subash Shankar',	'Shankar S.',		'17-DEC-1960', 'M', NULL, 8);
INSERT INTO VOTER VALUES (42,	'Shanmugam R.',		'Raviraman D.',		'11-DEC-1947', 'M', NULL, 8);
INSERT INTO VOTER VALUES (43,	'Manish Agarwal',	'Ramesh Agarwal',	'11-OCT-1949', 'M', NULL, 8);
INSERT INTO VOTER VALUES (44,	'Jeevan J.',		'Jagan Krishnan',	'13-JAN-1980', 'M', NULL, 8);
INSERT INTO VOTER VALUES (45,	'Raja C.',		'Chockalingam N.',	'19-FEB-1962', 'M', NULL, 8);
INSERT INTO VOTER VALUES (46,	'Nandhini Bala',	'Balaji Mohan',		'09-MAR-1961', 'F', NULL, 8);
INSERT INTO VOTER VALUES (47,	'Shanmathi R.',		'Ram Narayanan',	'17-DEC-1998', 'F', NULL, 9);
INSERT INTO VOTER VALUES (48,	'Felix Antony',		'Mark Antony',		'02-NOV-2001', 'M', NULL, 9);
INSERT INTO VOTER VALUES (49,	'Indra Devi',		'Sashee Kiran',		'07-SEP-2000', 'F', NULL, 9);
INSERT INTO VOTER VALUES (50,	'Natarajan T.',		'Tamizhselvan R.',	'11-DEC-1983', 'M', 'SC', 9);
INSERT INTO VOTER VALUES (51,	'Niranjana N.',		'Narayanan R.',		'01-APR-1999', 'M', NULL, 9);
INSERT INTO VOTER VALUES (52,	'Jagan Ramesh',		'Ramesh Ravi',		'23-JAN-1978', 'M', NULL, 10);
INSERT INTO VOTER VALUES (53,	'Haider Ali',		'Yusuf Ali Baig',	'30-OCT-1976', 'M', NULL, 10);
INSERT INTO VOTER VALUES (54,	'Naren T.',		'Thiruvenkataswami S.',	'24-JUL-2001', 'M', NULL, 10);
INSERT INTO VOTER VALUES (55,	'Gopal T.',		'Tamizhan R.',		'12-JAN-1990', 'M', 'SC', 10);
INSERT INTO VOTER VALUES (56,	'Saatvik Reddy',	'Nimish Reddy',		'11-APR-1973', 'M', NULL, 10);
INSERT INTO VOTER VALUES (57,	'Vijeesh M.',		'Mohinish P.',		'19-JUL-1955', 'M', NULL, 10);
INSERT INTO VOTER VALUES (58,	'Ramanth Rao',		'Suresh Rao',		'12-FEB-1995', 'M', NULL, 11);
INSERT INTO VOTER VALUES (59,	'Hanuma Rayudu',	'Ambati Rayudu',	'04-FEB-1954', 'M', NULL, 11);
INSERT INTO VOTER VALUES (60,	'Sheldon Jackson',	'Jackson Royston',	'03-MAR-1993', 'M', NULL, 11);
INSERT INTO VOTER VALUES (61,	'Parimalar L.',		'Logasundar B.',	'01-AUG-1967', 'F', NULL, 11);
INSERT INTO VOTER VALUES (62,	'Soundharya V.',	'Vijayan G.',		'29-JUN-1976', 'F', NULL, 11);
INSERT INTO VOTER VALUES (63,	'Vamsi R.',		'Rajnish N.',		'27-MAY-1966', 'M', NULL, 11);
INSERT INTO VOTER VALUES (64,	'Javed Miandad',	'Misbah Miandad',	'05-DEC-1963', 'M', 'SC', 12);
INSERT INTO VOTER VALUES (65,	'Aashiq Miandad',	'Misbah Miandad',	'07-NOV-1965', 'M', 'SC', 12);
INSERT INTO VOTER VALUES (66,	'Adyanth Manu',		'Manu Indreesh',	'23-SEP-2002', 'M', NULL, 12);
INSERT INTO VOTER VALUES (67,	'Smrithi Anish',	'Anish Rajesh',		'13-OCT-1992', 'F', 'SC', 12);
INSERT INTO VOTER VALUES (68,	'Tejas Shreeshanth',	'Shreeshanth Santhan',	'13-APR-1991', 'M', NULL, 12);
INSERT INTO VOTER VALUES (69,	'Arya Raman',		'Raman C.',		'06-MAR-1939', 'F', NULL, 12);
INSERT INTO VOTER VALUES (70,	'Natarajan P.',		'Paribhashan R.',	'26-JUL-1944', 'M', NULL, 13);
INSERT INTO VOTER VALUES (71,	'Anthony Vasquez',	'Lucas Vasquez',	'09-AUG-1994', 'M', NULL, 13);
INSERT INTO VOTER VALUES (72,	'Rajan T.',		'Tamizhan J.',		'19-OCT-1941', 'M', NULL, 13);
INSERT INTO VOTER VALUES (73,	'Himesh Reshammiya',	'Jignesh Reshammiya',	'16-DEC-1992', 'M', NULL, 13);
INSERT INTO VOTER VALUES (74,	'Jitesh S.',		'Suranga Lakmal',	'17-DEC-1982', 'M', NULL, 13);
INSERT INTO VOTER VALUES (75,	'Sivapriya G.',		'Gopalan R.',		'09-NOV-1981', 'F', NULL, 13);
INSERT INTO VOTER VALUES (76,	'Harini T.',		'Thangapandi R.',	'13-SEP-1970', 'F', NULL, 14);
INSERT INTO VOTER VALUES (77,	'Niroshan Mathew',	'Rajesh Jacob',		'24-FEB-1991', 'M', NULL, 14);
INSERT INTO VOTER VALUES (78,	'Mayavan S.',		'Suparnan K. L.',	'03-OCT-1992', 'M', 'SC', 14);
INSERT INTO VOTER VALUES (79,	'Rohit Midha',		'Ishan Midha',		'09-DEC-1997', 'M', NULL, 14);
INSERT INTO VOTER VALUES (80,	'Kamal Singh',		'Piyush Singh',		'02-NOV-1999', 'M', NULL, 14);
INSERT INTO VOTER VALUES (81,	'Russell Arnold',	'Arnold Johnson',	'06-AUG-1965', 'M', NULL, 15);
INSERT INTO VOTER VALUES (82,	'Fakhar Ali',		'Imran Ali',		'02-JUN-1951', 'M', NULL, 15);
INSERT INTO VOTER VALUES (83,	'Somdev Ravichandran',	'Ravichandran K.',	'22-MAY-1953', 'M', NULL, 15);
INSERT INTO VOTER VALUES (84,	'Jawahar Srinath',	'Srinath Selvan',	'15-MAY-1995', 'M', NULL, 15);
INSERT INTO VOTER VALUES (85,	'Swathi Balaji',	'Balaji Damodharan',	'14-MAY-1996', 'F', NULL, 15);
INSERT INTO VOTER VALUES (86,	'Nagarajan D.',		'Devaraiyan C.',	'02-OCT-1974', 'M', NULL, 15);
INSERT INTO VOTER VALUES (87,	'Marco Cesar',		'Bosco Cesar',		'10-APR-1978', 'M', NULL, 16);
INSERT INTO VOTER VALUES (88,	'Mushtaq Ahmed',	'Syed Abbas',		'27-JAN-1936', 'M', 'SC', 16);
INSERT INTO VOTER VALUES (89,	'Meera Swamy',		'Swamy Nathan',		'28-NOV-1959', 'F', NULL, 16);
INSERT INTO VOTER VALUES (90,	'Rabinder Kannan',	'Kannan Ashwin',	'31-DEC-1987', 'M', NULL, 16);
INSERT INTO VOTER VALUES (91,	'Ravish Ghosh',		'Satyajit Ghosh',	'21-MAY-1952', 'M', NULL, 16);
INSERT INTO VOTER VALUES (92,	'Anjali Satish',	'Satish Menon',		'31-DEC-2002', 'F', NULL, 16);


INSERT INTO CANDIDATE VALUES (1,	'B. John Pandian',	1, 	65, 1, 'SC');
INSERT INTO CANDIDATE VALUES (2,	'I. Paranthamen', 	2, 	44, 1, 'SC');
INSERT INTO CANDIDATE VALUES (3,	'Gunasekar N.',		999, 	31, 1, 'SC');
INSERT INTO CANDIDATE VALUES (4,	'Jayakalpana',  	999, 	50, 1, 'SC');
INSERT INTO CANDIDATE VALUES (5,	'Gokula Indira', 	1, 	55, 2, NULL);
INSERT INTO CANDIDATE VALUES (6,	'MK Mohan', 		2, 	68, 2, NULL);
INSERT INTO CANDIDATE VALUES (7,	'P. Manimaran', 	999, 	55, 2, NULL);
INSERT INTO CANDIDATE VALUES (8,	'VM Nagarajan', 	999, 	65, 2, NULL);
INSERT INTO CANDIDATE VALUES (9,	'MK Ashok',	 	1, 	49, 3, NULL);
INSERT INTO CANDIDATE VALUES (10,	'Aasaan Maulana', 	4, 	36, 3, NULL);
INSERT INTO CANDIDATE VALUES (11,	'G. Yesudasan', 	999, 	69, 3, NULL);
INSERT INTO CANDIDATE VALUES (12,	'Mariappan T.', 	999, 	55, 4, NULL);
INSERT INTO CANDIDATE VALUES (13,	'Shanmugasundaram TR', 	2, 	59, 4, NULL);
INSERT INTO CANDIDATE VALUES (14,	'Selvaraj AK', 		1, 	62, 4, NULL);
INSERT INTO CANDIDATE VALUES (15,	'V. Jayaraman', 	1, 	67, 5, NULL);
INSERT INTO CANDIDATE VALUES (16,	'Varadharajan K.', 	2, 	69, 5, NULL);
INSERT INTO CANDIDATE VALUES (17,	'Muthukumarasamy R.', 	999, 	46, 5, NULL);
INSERT INTO CANDIDATE VALUES (18,	'Aruchamy C.M.', 	5, 	56, 5, NULL);
INSERT INTO CANDIDATE VALUES (19,	'Palani',	 	1, 	69, 6, NULL);
INSERT INTO CANDIDATE VALUES (20,	'Selvaperunthaigai', 	4, 	60, 6, NULL);
INSERT INTO CANDIDATE VALUES (21,	'Manickam K.',	 	1, 	55, 7, 'SC');
INSERT INTO CANDIDATE VALUES (22,	'Yoganathan S.', 	6, 	42, 7, 'SC');
INSERT INTO CANDIDATE VALUES (23,	'Sekar N.',	 	999, 	52, 7, 'SC');
INSERT INTO CANDIDATE VALUES (24,	'Ayyapan P.',	 	3, 	56, 8, NULL);
INSERT INTO CANDIDATE VALUES (25,	'Sundar C.',	 	999, 	55, 8, NULL);
INSERT INTO CANDIDATE VALUES (26,	'Kamalakaran D.', 	6, 	44, 8, NULL);
INSERT INTO CANDIDATE VALUES (27,	'Thanikachalam M.', 	5, 	72, 8, NULL);
INSERT INTO CANDIDATE VALUES (28,	'Palaniyandi M.', 	2, 	54, 9, NULL);
INSERT INTO CANDIDATE VALUES (29,	'Kupa Krishnan', 	1, 	69, 9, NULL);
INSERT INTO CANDIDATE VALUES (30,	'Daniel Jude Martin', 	6, 	41, 9, NULL);
INSERT INTO CANDIDATE VALUES (31,	'Sethumadhavan', 	999, 	48, 9, NULL);